apiVersion: v1
kind: Secret
metadata:
  name: sap-secrets
  namespace: sap-erp
type: Opaque
data:
  jwtSecret: ZGdocGNzaXpadXhZZ3VyZWp3ZHRzZWN5bGV+a2V5Zm9yc2FwZXJwc3lzdGVtZG9ub3R1c2VpbnByb2R1Y3Rpb24=
  dbUser: c2FwX3VzZXI=
  dbPass: c2FwX3Bhc3M=
